# Generated by Django 5.2.17 on 2026-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='output_filename',
            field=models.CharField(blank=True, help_text='Friendly filename shown to the user on download', max_length=255),
        ),
    ]
