services:
  - type: web
    name: pdfmaster
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: AI_API_KEY
        value: ""
      - key: AI_PROVIDER
        value: "groq"
      - key: AI_BASE_URL
        value: "https://api.groq.com/openai/v1"
      - key: AI_DEFAULT_MODEL
        value: "llama-3.3-70b-versatile"
      - key: AI_TIMEOUT_SECONDS
        value: "30"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
    plan: free
