# Generated by Django 5.2.17 on 2026-08-15 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ai_uploads/')),
                ('tool', models.CharField(choices=[('summarize', 'Summarize PDF'), ('extract', 'Extract Text'), ('translate', 'Translate Text'), ('ask', 'Ask Question')], max_length=20)),
                ('prompt', models.TextField(blank=True, help_text='User question or instruction')),
                ('response', models.TextField(blank=True, help_text='AI-generated response')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
