# Generated by Django 5.2.17 on 2026-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='tool',
            field=models.CharField(choices=[('summarize', 'Summarize PDF'), ('extract', 'Extract Text'), ('translate', 'Translate Text'), ('ask', 'Ask Question'), ('quiz', 'AI Quiz Generator'), ('flashcards', 'Flashcard Generator'), ('study_notes', 'Study Notes'), ('study_guide', 'Study Guide'), ('question_bank', 'Question Bank'), ('important_questions', 'Important Questions'), ('chapter_summary', 'Chapter Summary'), ('key_concepts', 'Key Concepts'), ('exam_prep', 'Exam Preparation')], max_length=25),
        ),
    ]
